apiVersion: v1
kind: ConfigMap
metadata:
  name: ms-lista-espera-config
  labels:
    app: ms-lista-espera
data:
  SERVER_PORT: "8081"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-lista-espera:5432/lista_espera_db"
  SPRING_DATASOURCE_USERNAME: "rednorte"
  SPRING_FLYWAY_ENABLED: "true"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "validate"
