apiVersion: v1
kind: Service
metadata:
  name: postgres-lista-espera
  labels:
    app: postgres-lista-espera
spec:
  type: ClusterIP
  selector:
    app: postgres-lista-espera
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
